services:
  - type: web
    name: mscliente
    env: docker
    repo: https://github.com/ruke-duoc-uc/bosques-australes.git
    plan: free
    region: oregon
    healthCheckPath: /api/cliente
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8081
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: mscliente-db
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: mscliente-db
          property: port
      - key: SPRING_DATASOURCE_DBNAME
        fromDatabase:
          name: mscliente-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mscliente-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mscliente-db
          property: password

databases:
  - name: mscliente-db
    plan: free
    region: oregon
